# Preface {.unnumbered}

## Preface to the Second Edition
This book is addressed to those who enjoy solving non-standard mathematical problems.

The specificity of distance learning and correspondence, "home" olympiads is that problems are given for an extended period. With such unhurried research work, it's natural not only to solve a specific problem but also to find its generalizations and connections with other problems.

The book's goal is to help the reader in this work. Behind disparate facts, we tried to see the contours of important mathematical concepts and constructions, to show that the generalization of relatively simple problems sometimes leads to the forefront of mathematics.

The first paragraph of the book contains various entertaining problems that are diverse in content and simple in formulation.

In each of the following five paragraphs, the problem statements are followed by their discussion: first, an elementary solution is provided, then in most cases (after the ∇ sign) a generalization is suggested, and sometimes (after the words "for experts") there's more difficult text using the terminology of modern mathematics. Each of these paragraphs ends with a large list of problems for independent solving; in addition to questions close to those already discussed, new research topics are also included.

An extensive bibliography at the end of the book indicates the main sources we used and is designed to give readers the opportunity to delve deeper into the problem that interested them.

In the five years since the first edition of the book, we have received many letters and reviews from mathematics enthusiasts. Some problems were used in various in-person and correspondence mathematical competitions, served as the basis for student reports at mathematical conferences; assignments were given to students of the correspondence mathematics school based on the book.

This experience was taken into account when revising the book. Many problems have been added, in particular, problem cycles have been compiled: solving equations in integers, divisibility of polynomials, geometric constructions, proving inequalities, sequences; new topics have also been included in the paragraph "Unusual examples and constructions". We tried to arrange the problems for independent solving and provide hints in such a way as to help the reader repeat the main reasoning techniques.

We would like to express our deep gratitude to Academician I.M. Gelfand, Chairman of the Scientific Council of the All-Union Correspondence Mathematical School, for his constant attention to our work and valuable criticism. Among the mathematicians whose books and advice influenced our work, V.I. Arnold, M.I. Bashmakov, V.G. Boltyansky, N.N. Vorobyov, M.L. Gerver, P.B. Gusyatnikov, Ya.G. Sinai, D.B. Fuchs, I.M. Yaglom, G.N. Yakovlev should be named first. M.I. Zhgenti, A.V. Karzanov, E.B. Kikodze, A.K. Kovaldji, N.N. Konstantinov, S.M. Lvovsky, P.I. Masarskaya, N.E. Sokhor, A.A. Tretyakov, A.Kh. Shen, M.V. Yakobson and many other our friends and colleagues shared useful suggestions, problems, and experience of working with the book. We are grateful for the help in preparing the manuscript to N.Yu. Vaisman, L.G. Serebrennikova, L.V. Chernova, and especially to S.L. Tabachnikov, whose participation significantly exceeded the duties of an editor.

## Preface to the Third Edition

It has been 25 years since the second edition of our book. During this time, it has been repeatedly used for assignments to students of the mathematical department of VZMS and S-Z MS (respectively, All-Union - then All-Russian - and North-Western correspondence schools), as well as in various competitions and in teaching schoolchildren in our country and abroad.

In 1998, one of the authors of the book, Nikolai Borisovich Vasiliev, an outstanding mathematician, teacher, and educator, passed away. Therefore, this edition was prepared for printing without his usually very productive participation.

However, the text remained largely unchanged. The solution to one problem (11-23) has been corrected, solutions to several problems (11-1, 5-12, 5-20, 5-21, 6-10, 6-13) have been supplemented. And, of course, if something was written as "recent" in the second edition, now it had to be replaced with more precise references due to the passage of time. A thematic index has been added.

We would like to thank all our colleagues and friends who helped us with their advice in working on this edition. In addition to the mathematicians and educators listed in the preface to the second edition, we would like to mention R. Zigangirov, Yu.I. Ionin, A.G. Kushnirenko, L. Levin, Yu.P. Solovyev, I.F. Sharygin, E.Ya. Gik. We are grateful to the director of MCCME I.V. Yashchenko for his attention to this book.

We request readers to send letters with constructive criticism and feedback about the book to the address of MCCME Publishing House.

The Authors
